# -*- coding: utf-8 -*-
"""postprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1brDRob4BCWGUucbrGF6bFZg63uAiuK0z
"""

import tensorflow as tf
import numpy as np
import librosa

def convert_to_audio(data):
  ''' reconvert prediction to audio
  
    Keyword arguments:
    dataset -- the dataset to be sampled from
  '''
  #reverse the nromalisation
  S = data*40-40 +20
  #convert mel-spectogram to audio
  S = librosa.db_to_power(S, ref=1.0)
  S = librosa.feature.inverse.mel_to_audio(S, sr=16000, n_fft=1024,hop_length=256, win_length= 1024)
  #returns the audio data
  return S
  
def get_phase(data):
  ''' get phase information from data
  
    Keyword arguments:
    dataset -- the dataset to be sampled from
  '''
  phase = []
  for i in range(len(data)):
    spectrogram = librosa.stft(data[i], n_fft=2048, hop_length=256, window='hann')
    phase.append(np.angle(spectrogram))
  return np.array(phase)
